/**
 * The to-do list, as a brief an agent can work from.
 *
 * The list itself is a selection, not a plan: five changes with the evidence each one rests on. Handed over as
 * five lines, the taker has to guess where the evidence lives, what "done" means, and how anything will be
 * measured afterwards. This turns it into the whole loop: the data sources with the path for each, the steps
 * from evidence to a verified change, what to run, and how the next days' sessions decide whether the change
 * stays. Every command named here exists in this repository, and every path is one a reader can open.
 */

/** One task, as the brief draws it: the fields a to-do entry carries (`TodoItem`), and nothing else. */
const NO_FIELD = "not stated";
const value = (text) => (text && String(text).trim() ? String(text).trim() : null);

/** A raw markdown document. One task per `- **...**` block, so a reader can jump by heading. */
export function improvementBrief(items, { generatedAt = null, savedAt = null } = {}) {
  const count = items.length;
  const lines = [];
  const head = (text) => lines.push(`## ${text}`, "");
  const task = (index, item) => {
    const id = value(item.id) ?? `#${index + 1}`;
    const skill = value(item.skill) ?? "unknown skill";
    const day = value(item.day);
    lines.push(`### ${index + 1}. ${skill} (${id}${day ? `, proposed ${day}` : ""})`, "");
    lines.push(`**Change:** ${value(item.change) ?? NO_FIELD}`, "");
    if (value(item.reason)) lines.push(`**Why:** ${value(item.reason)}`, "");
    if (value(item.signal)) lines.push(`**The signal that blames it:** ${value(item.signal)}`, "");
    lines.push(`**Where it lives:** ${value(item.target) ?? NO_FIELD}`, "");
    lines.push(`**The check that proves it:** ${value(item.expected) ?? NO_FIELD}`, "");
    if (value(item.route)) lines.push(`**How the repository would do it:** ${value(item.route)}`, "");
    if (value(item.note)) lines.push(`**The reader's note:** ${value(item.note)}`, "");
    if (day) {
      lines.push(
        `**Its evidence:** the day's pack is \`.x-skills/daily/${day}/summary.json\` (its \`signals[]\` carry the ` +
          `session ids, message numbers and excerpts) and its review is \`.x-skills/daily/${day}/DIGEST.md\`; ` +
          `over HTTP the same day is \`/api/day/${day}\`, and a session it names opens at ` +
          `\`/day/${day}/session/<id>\`. Match the signal text above against \`signals[].summary\` to find the ` +
          `session it came from.`,
        ""
      );
    } else {
      const session = value(item.signal)?.match(/\b[0-9a-f]{16}\b/)?.[0] ?? null;
      lines.push(
        "**Its evidence:** this item carries no day (it was kept before the list recorded one). " +
          (session
            ? `The signal names the session it came from, and the day it is in is the one whose pack holds it: ` +
              `\`grep -l ${session} .x-skills/daily/*/summary.json\`, then open that day.`
            : "The signal names no session, so ask the reader which day it came from."),
        ""
      );
    }
    lines.push("");
  };

  lines.push(`# Improving the skills: ${count} task${count === 1 ? "" : "s"} from the daily record`, "");
  lines.push(
    generatedAt
      ? `Generated ${generatedAt} by the report at http://127.0.0.1:8787/todos.`
      : "Generated by the report at http://127.0.0.1:8787/todos.",
    ""
  );
  lines.push(
    `You are the agent taking this on. Each task below is a measured weakness of a skill in \`skills/\`, with the ` +
      `evidence it came from, the file and check it names, and the way the next days' sessions will judge it. ` +
      `Work them one at a time, in the order given, and finish each loop before starting the next.` +
      (savedAt ? ` The selection was last written ${savedAt} and lives in \`.x-skills/daily/todos.json\`.` : ""),
    ""
  );

  head("Where the data is");
  lines.push(
    "Nothing here is a guess: every claim in a task can be traced to one of these.",
    "",
    "| What | Where | What it holds |",
    "|---|---|---|",
    "| The record | `.x-skills/daily/history.jsonl` | one line per day: `date`, `sessions`, `weights`, `floor`, and `skills[]` with `name`, `score`, `raw`, `n`, `named`, `dimensions`, `status`. This is the only source of numbers in the report. |",
    "| A day's evidence pack | `.x-skills/daily/<date>/summary.json` | the window, which CLI stores were read (`hosts[]`), every session (host, stats, skills loaded and used, checks, graphs, transcript path), every signal (`id`, `kind`, `severity`, `count`, `suspects`, `session`, `evidence`), and the path transcripts were written to. |",
    "| A day's review | `.x-skills/daily/<date>/DIGEST.md` | the proposals, each with its signal, target, change, reason and check. The proposals in this brief were read from there. |",
    "| The selection | `.x-skills/daily/todos.json` | this list: `id`, `day`, `skill`, `change`, `reason`, `expected`, `target`, `route`, `signal`, `note`. |",
    "| The report | `npm run report` (http://127.0.0.1:8787) | the same record, rendered: `/` for the scores, `/day/<date>` for a day, `/skill/<name>` for one skill's line, its signals and the proposals that targeted it. |",
    "| The report's API | `/api/movement`, `/api/days`, `/api/day/<date>`, `/api/day/<date>/session/<id>`, `/api/skill/<name>`, `/api/todos`, `/history.jsonl` | the same data as JSON, for anything that is not the app. |",
    "| A session's transcript | the `transcripts` directory named in `summary.json` (for example `/tmp/xskills-reflection/<date>/`), or the store the session came from (`skills/x-autoreflection/scripts/hosts/`) | megabytes each: read the window around the message numbers a signal cites, and never copy one into the repository. |",
    "| A run folder | `.x-skills/runs/<date>-<id>-<slug>/` | what the planning skills wrote for a piece of work: `E00-plan.md`, `E01-epic.md`, `E02-tasks/`, a reflection, and the fix plan `x-fix` reads. |",
    "| Fresh evidence | `node automation/daily-reflection/collect-sessions.mjs` (`--hours 168`, `--host crush,codex`, `--check`) | collects a new pack now. `--check` only probes: exit 1 means no x-skill was used in the window, exit 3 means no host could be read. |",
    "| How a score is made | `skills/x-autoreflection/scripts/metrics.mjs` (`WEIGHTS_V1`, `SAMPLE_FLOOR`, `historyLine`) and `scripts/derive.mjs` | the five axes (`conformance`, `adherence`, `trigger`, `rework`, `protocol`), their weights, and the floor of 5 loaded sessions under which a day has a sample size rather than a score. |",
    "",
    "The daily automation (`x-skills-daily-reflection`, 05:00) adds one line to `history.jsonl` per day, so a " +
      "change made today is measured by the sessions of tomorrow:",
    "",
    "```bash",
    "npm test                                  # every test in the repository",
    "npm run check:run-folders                 # the run-folder helpers are generated, and must match",
    "node skills/x-skill-lint/scripts/lint.mjs # a skill file changed: frontmatter, refs, README table",
    "node automation/daily-reflection/collect-sessions.mjs   # collect now, if you cannot wait for 05:00",
    "npm run report                            # the scores as they stand",
    "```",
    ""
  );

  head("Which skill does which step");
  lines.push(
    "| Step | Skill |",
    "|---|---|",
    "| Understand the weakness | `x-analyze` (a thesis with cited evidence), `x-investigate` (root cause, hypotheses eliminated in order), `x-triage` (a bug's platform and evidence before any tool runs) |",
    "| Get something that fails | `x-reproduce`: the smallest script or case that exits 1 while the bug is present |",
    "| Plan it when it is bigger than one edit | `x-plan` (a spec), `x-epic` (the outcome as layers), `x-decompose` (tasks an agent can hold) |",
    "| Change it | `x-fix` (work a fix plan, verify, mark it done), `x-implement` (TDD, one layer at a time, parallel tasks via `x-parallel`) |",
    "| Review it | `x-review` (the diff, against the repository's principles), `x-roast` (a claim or a spec in prose), `x-skill-lint` (the repository's own skills) |",
    "| Undo it | `x-rollback` (a revert, with the impact stated first) |",
    "| Land it | `x-commit` (one line, in the repository's convention) |",
    "| Improve the loop itself | `x-autoreflection`: read a session's transcript, find the friction, propose the skill change that removes it |",
    ""
  );

  head("The loop, once per task");
  lines.push(
    "1. **Read the task and its evidence.** Open the target file and the day's pack. Read the signal's excerpt " +
      "and the session around it. What the session shows is the fact; the summary is a summary.",
    "2. **State the cause in one sentence, as a rule.** \"X happens because Y\" is workable; \"X is bad\" is not. " +
      "`x-analyze` is the skill for this, and `x-investigate` when the cause is not visible yet.",
    "3. **Reproduce it.** Before the edit, have something that fails: a test, a scenario, or the analyzer run by " +
      "hand. `x-reproduce` writes the smallest one. A change with no failing case in front of it is a guess.",
    "4. **Make the smallest change that removes the cause.** One thing, with its test in the same change. Use " +
      "the route the task names when it names one (`x-fix` for a planned fix, `x-plan` when a decision is " +
      "missing, `x-implement` when the work is a layer of a larger plan).",
    "5. **Prove it with the task's own check.** Run the command the task names. It has to pass on its own terms: " +
      "not by widening a test, not by skipping a case, not by catching an error the code was meant to raise.",
    "6. **Run the repository's gates.** `npm test` for everything, `npm run check:run-folders` if you touched a " +
      "skill's scripts, `node skills/x-skill-lint/scripts/lint.mjs` if you touched a `SKILL.md` or a reference. " +
      "A skill that ships a scenario has its own command; run that too.",
    "7. **Review the diff as a stranger would.** `x-review` for the code, `x-roast` or a second pair of eyes for " +
      "a claim in prose. Then `x-fix` what the review found. Green tests are not a review.",
    "8. **Say what changed and why, in the commit.** `x-commit` writes one line in the repository's convention; " +
      "the reason belongs in the body when it is not obvious from the change.",
    "9. **Let it be measured.** Nothing here is verified by the author. The score moves only when sessions that " +
      "used the skill are scanned, which happens at the next 05:00, or now with the collector.",
    "10. **Keep or revert by the number, and record the decision.** Read the skill's line in the report: `/skill/<name>` " +
      "shows the score, the `n` behind it and the sample floor. A day under the floor is an `n`, not a score. If " +
      "the line goes the wrong way, `x-rollback` undoes it and the reason is written down rather than lost.",
    "",
    "One task, one change, one measurement. Two changes in one commit cannot be told apart afterwards, and the " +
      "record is the only thing that says which of them worked.",
    ""
  );

  head(`The tasks${count ? ` (${count})` : ""}`);
  if (!count) {
    lines.push("The selection is empty: open a day in the report and use `+ to-do` on a proposal.", "");
  } else {
    for (const [index, item] of items.entries()) task(index, item);
  }

  head("What not to do");
  lines.push(
    "- Do not edit `history.jsonl` or a day's pack: they are the record. A number that was not measured is worse " +
      "than a missing one.",
    "- Do not widen a test to make it pass, and do not silence an error to make a run green. `x-fix` treats a " +
      "silenced failure as an unfinished fix.",
    "- Do not bundle unrelated changes into one commit; the measurement cannot tell them apart.",
    "- Do not copy a transcript into the repository: they are megabytes, and they are other people's sessions.",
    "- Do not treat a task as done because the code changed. Done is the check passing, the gates passing, and " +
      "the next measured days agreeing.",
    ""
  );

  head("When the work lands");
  lines.push(
    "- The proposal's own claim is testable: the check in the task is the thing to re-read first.",
    "- The skill's line is at `/skill/<name>`, and the day it moved is at `/day/<date>`.",
    "- The reader's list is `.x-skills/daily/todos.json`: an item is removed from the to-do screen (the `remove` " +
      "button), which is also what stops a day's proposal from offering itself again.",
    "- If a task turns out to be wrong (the evidence does not support it, or the fix is not worth its risk), say " +
      "so and remove it from the list: a rejected proposal with a reason is a result.",
    ""
  );

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
